### ISSUE TITLE
2FE0..2FEF 缺失报错

### ISSUE THREAD

**Issue by hwnzy** [TakWolf/unidata-blocks#1]
建议在`Blocks.txt`中添加 `2FE0..2FEF; Unassigned`

参考：https://unifoundry.com/unifont/index.html

**Comment by TakWolf** [comment]
`Unassigned` 不就是未分配吗？所以查询返回 None 应该是正确预期行为啊。

（按照官方建议，未匹配应该返回 `0000..10FFFF; No_Block`，但在 python 中返回 None 更合适）

另外 https://www.unicode.org/Public/UNIDATA/Blocks.txt 是官方标准数据库文件。只会同步最新版本，不应该做任何修改。

**Comment by hwnzy** [comment]
这样子，我是使用缝合怪字体项目的 dump_service.py 发现的这个问题

**Comment by TakWolf** [comment]
我懂了，你发现其他字体中有注册在 2FE0..2FEF 区块范围的字符是吧。

这个 block 只是用来分配字形目录的

你加一个判断，如果 `block is None`, 虚构一个 `0000..10FFFF; No_Block` 的 `UnicodeBlock` 结构
或者你给你默认目录都行

**Comment by hwnzy** [comment]
OK，晚安
